---
- name: Configure web server for OpenAGI
  hosts: webservers
  become: yes
  become_user: root

  tasks:
    - name: Update APT and install Nginx
      apt:
        update_cache: yes
        name: nginx
        state: present

    - name: Copy index.html to the server
      copy:
        src: ../site/index.html
        dest: /var/www/html/index.html

    - name: Copy styles.css to the server
      copy:
        src: ../site/styles.css
        dest: /var/www/html/styles.css

    - name: Copy Nginx configuration file to the server
      copy:
        src: ../nginx/openagi.conf
        dest: /etc/nginx/sites-available/openagi.conf

    - name: Create symbolic link to enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/openagi.conf
        dest: /etc/nginx/sites-enabled/openagi.conf
        state: link

    - name: Remove the default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
